**Arewa Data Science Academy**

**Deep Learning Cohort1.0**

Name: Abba Nasir Muazu

Email: abbanasir@gmail.com

Title: Week 1 Solution

**Exercises Solution**

In [1]:
import torch

In [15]:
random_tensor_A = torch.rand(3, 7)
random_tensor_A

tensor([[0.2675, 0.7051, 0.4969, 0.3176, 0.5077, 0.7735, 0.3021],
        [0.9847, 0.3359, 0.5843, 0.1949, 0.7525, 0.4699, 0.1569],
        [0.7617, 0.0090, 0.6502, 0.8501, 0.6402, 0.9372, 0.2868]])

In [5]:
random_tensor_B = torch.rand(1, 7)
random_tensor_B

tensor([[0.7497, 0.5188, 0.0600, 0.1345, 0.3453, 0.4575, 0.1212]])

In [16]:
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.2675, 0.7051, 0.4969, 0.3176, 0.5077, 0.7735, 0.3021],
        [0.9847, 0.3359, 0.5843, 0.1949, 0.7525, 0.4699, 0.1569],
        [0.7617, 0.0090, 0.6502, 0.8501, 0.6402, 0.9372, 0.2868]])
tensor([[0.7497, 0.5188, 0.0600, 0.1345, 0.3453, 0.4575, 0.1212]])


In [17]:
print(random_tensor_A)
print(random_tensor_B.T)

tensor([[0.2675, 0.7051, 0.4969, 0.3176, 0.5077, 0.7735, 0.3021],
        [0.9847, 0.3359, 0.5843, 0.1949, 0.7525, 0.4699, 0.1569],
        [0.7617, 0.0090, 0.6502, 0.8501, 0.6402, 0.9372, 0.2868]])
tensor([[0.7497],
        [0.5188],
        [0.0600],
        [0.1345],
        [0.3453],
        [0.4575],
        [0.1212]])


In [18]:
torch.mm(random_tensor_A, random_tensor_B.T)

tensor([[1.2047],
        [1.4676],
        [1.4136]])

In [31]:
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(7, 7)
random_tensor_C

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [32]:
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(1, 7)
random_tensor_D

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [33]:
print(random_tensor_C)
print(random_tensor_D.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])


In [34]:
torch.mm(random_tensor_C, random_tensor_D.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [35]:
torch.manual_seed(1234)
random_tensor_E = torch.rand(2, 3)
random_tensor_E


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

In [36]:
torch.manual_seed(1234)
random_tensor_F = torch.rand(2, 3)
random_tensor_F

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

In [39]:
print(random_tensor_E)
print(random_tensor_F.T)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0290, 0.3666],
        [0.4019, 0.0583],
        [0.2598, 0.7006]])


In [40]:
torch.mm(random_tensor_E, random_tensor_F.T)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [42]:
x =torch.mm(random_tensor_E, random_tensor_F.T)
x

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [43]:
torch.max(x), torch.min(x)

(tensor(0.6287), tensor(0.2161))

In [44]:
torch.argmax(x), torch.argmin(x)

(tensor(3), tensor(1))

In [45]:
random_tensor_G = torch.rand(1, 1, 1, 10)
random_tensor_G

tensor([[[[0.0518, 0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208,
           0.2793, 0.6817]]]])

In [ ]:
random_tensor_H = torch.rand()